-- Run this in Supabase SQL Editor to create auth table + seed accounts.
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'student')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE OR REPLACE FUNCTION public.set_users_updated_at() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trg_users_updated_at ON public.users;
CREATE TRIGGER trg_users_updated_at BEFORE
UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_users_updated_at();
INSERT INTO public.users (email, username, password_hash, role, is_active)
VALUES (
    'jennypatanag@gmail.com',
    'jen25',
    '$2b$12$waYZbff4Hba7QUsWdYP7l.iPL.BOkAgJwOM732EtHB4CbD3ed8vsC',
    'admin',
    TRUE
  ),
  (
    'hermoso_lyrika@plpasig.edu.ph',
    'leeRiKang',
    '$2b$12$JBRsGLGl3Ym4YgWXvM.mguzweGLw7/m0GgAYCU6IjxE1vcYrCOy.6',
    'student',
    TRUE
  ) ON CONFLICT (username) DO
UPDATE
SET email = EXCLUDED.email,
  password_hash = EXCLUDED.password_hash,
  role = EXCLUDED.role,
  is_active = TRUE;
SELECT id,
  email,
  username,
  role,
  is_active,
  created_at,
  updated_at
FROM public.users
ORDER BY id;